name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag name
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Zip current directory
        id: prep
        run: |
          ZIP_NAME=Oasis-Resourcepack-${{ steps.tag.outputs.tag }}.zip
          zip -r "$ZIP_NAME" . -x ".git/*" ".github/*" ".vscode/*" "README.md" "LICENSE*" "CHANGELOG.md"
          echo "asset=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.prep.outputs.asset }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}